/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbs_module2;
import java.awt.Color;

/**
 *
 * @author StylishDheeru
 */
public class Input2 extends javax.swing.JFrame {

    /**
     * Creates new form Input2
     */
    public Input2() {
        initComponents();
        //outfld.setVisible(false);
        //outfld.setText("thopu");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inp_jlbl = new javax.swing.JLabel();
        inp_jtxt = new javax.swing.JTextField();
        addjbtn = new javax.swing.JButton();
        searchjbtn = new javax.swing.JButton();
        displayjbtn = new javax.swing.JButton();
        reslbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayfld = new javax.swing.JTextArea();
        outfld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Calisto MT", 0, 10)); // NOI18N

        inp_jlbl.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        inp_jlbl.setForeground(new java.awt.Color(255, 255, 255));
        inp_jlbl.setText("Enter number:");

        inp_jtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inp_jtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inp_jtxtActionPerformed(evt);
            }
        });

        addjbtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addjbtn.setText("Add");
        addjbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjbtnActionPerformed(evt);
            }
        });

        searchjbtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchjbtn.setText("Search");
        searchjbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjbtnActionPerformed(evt);
            }
        });

        displayjbtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        displayjbtn.setText("Display");
        displayjbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayjbtnActionPerformed(evt);
            }
        });

        reslbl.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N
        reslbl.setForeground(new java.awt.Color(51, 51, 51));
        reslbl.setText("Result");

        displayfld.setEditable(false);
        displayfld.setBackground(new java.awt.Color(51, 51, 51));
        displayfld.setColumns(20);
        displayfld.setForeground(new java.awt.Color(255, 255, 255));
        displayfld.setLineWrap(true);
        displayfld.setRows(5);
        displayfld.setWrapStyleWord(true);
        jScrollPane1.setViewportView(displayfld);

        outfld.setBackground(new java.awt.Color(51, 51, 51));
        outfld.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(outfld, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(inp_jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inp_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addjbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(searchjbtn)
                .addGap(90, 90, 90)
                .addComponent(displayjbtn)
                .addGap(342, 342, 342))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inp_jlbl)
                    .addComponent(inp_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reslbl))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayjbtn)
                    .addComponent(searchjbtn)
                    .addComponent(addjbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(outfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   
    int bfr = 3;
    int global_depth = 1;
    Table t= new Table(global_depth,bfr);
    private void addjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjbtnActionPerformed
        // TODO add your handling code here:
        String inp = inp_jtxt.getText();
        inp_jtxt.setText("");
        outfld.setText("");
        outfld.setVisible(false);
        reslbl.setForeground(new Color(51,51,51));
        int key = Integer.parseInt(inp);
        t.insert(key,false);
        
    }//GEN-LAST:event_addjbtnActionPerformed

    private void searchjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjbtnActionPerformed
        // TODO add your handling code here:
        String inp = inp_jtxt.getText();
        
        outfld.setVisible(true);
        outfld.setText("");
        inp_jtxt.setText("");
        reslbl.setForeground(new Color(255,255,255));
        int key = Integer.parseInt(inp);
        t.search(key);
        outfld.setText(t.result);
       // outfld.setText("Sup punk");
        System.out.println("out: "+ t.result);
        if(t.result.equals("") == true){
            outfld.setText("Not Found");
        }
    }//GEN-LAST:event_searchjbtnActionPerformed

    private void displayjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayjbtnActionPerformed
        // TODO add your handling code here:
        t.show_table(false);
        displayfld.setText("");
        displayfld.setText(Table.sho);
    }//GEN-LAST:event_displayjbtnActionPerformed

    private void inp_jtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inp_jtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inp_jtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addjbtn;
    private javax.swing.JTextArea displayfld;
    private javax.swing.JButton displayjbtn;
    private javax.swing.JLabel inp_jlbl;
    private javax.swing.JTextField inp_jtxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField outfld;
    private javax.swing.JLabel reslbl;
    private javax.swing.JButton searchjbtn;
    // End of variables declaration//GEN-END:variables
}
