/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbs_module2;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author StylishDheeru
 */
public class Input2 extends javax.swing.JFrame {

    /**
     * Creates new form Input2
     */
    //int bfr;
    public Input2() {
        initComponents();
        //String bf = JOptionPane.showInputDialog(rootPane, "Input BFR: ");
       // bfr = Integer.parseInt(bf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inp_jlbl = new javax.swing.JLabel();
        inp_jtxt = new javax.swing.JTextField();
        addjbtn = new javax.swing.JButton();
        searchjbtn = new javax.swing.JButton();
        displayjbtn = new javax.swing.JButton();
        reslbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayfld = new javax.swing.JTextArea();
        outfld = new javax.swing.JTextField();
        Headlbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Calisto MT", 0, 10)); // NOI18N

        inp_jlbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        inp_jlbl.setForeground(new java.awt.Color(255, 255, 255));
        inp_jlbl.setText("Enter number  :");

        inp_jtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inp_jtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inp_jtxtActionPerformed(evt);
            }
        });

        addjbtn.setBackground(new java.awt.Color(51, 102, 0));
        addjbtn.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        addjbtn.setText("Add");
        addjbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjbtnActionPerformed(evt);
            }
        });

        searchjbtn.setBackground(new java.awt.Color(51, 102, 0));
        searchjbtn.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        searchjbtn.setText("Search");
        searchjbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjbtnActionPerformed(evt);
            }
        });

        displayjbtn.setBackground(new java.awt.Color(51, 102, 0));
        displayjbtn.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        displayjbtn.setText("Display");
        displayjbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayjbtnActionPerformed(evt);
            }
        });

        reslbl.setFont(new java.awt.Font("Footlight MT Light", 0, 16)); // NOI18N
        reslbl.setForeground(new java.awt.Color(51, 51, 51));
        reslbl.setText("Result :");

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));

        displayfld.setEditable(false);
        displayfld.setBackground(new java.awt.Color(51, 51, 51));
        displayfld.setColumns(20);
        displayfld.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        displayfld.setForeground(new java.awt.Color(255, 255, 255));
        displayfld.setLineWrap(true);
        displayfld.setRows(5);
        displayfld.setWrapStyleWord(true);
        jScrollPane1.setViewportView(displayfld);

        outfld.setEditable(false);
        outfld.setBackground(new java.awt.Color(51, 51, 51));
        outfld.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        outfld.setForeground(new java.awt.Color(255, 255, 255));
        outfld.setBorder(null);

        Headlbl.setBackground(new java.awt.Color(204, 204, 204));
        Headlbl.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Headlbl.setForeground(new java.awt.Color(255, 255, 255));
        Headlbl.setText("Extendible Hashing Tool");

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(reslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(outfld, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(inp_jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(inp_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(393, 393, 393))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(addjbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(searchjbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(displayjbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(345, 345, 345))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(Headlbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Headlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inp_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inp_jlbl))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayjbtn)
                    .addComponent(searchjbtn)
                    .addComponent(addjbtn))
                .addGap(41, 41, 41)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(outfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   
    int bfr = 3;
    
    int global_depth = 1;
    Table t= new Table(global_depth,bfr);
    private void addjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjbtnActionPerformed
        // TODO add your handling code here:
        String inp = inp_jtxt.getText();
        inp_jtxt.setText("");
        outfld.setText("");
       // outfld.setVisible(false);
        reslbl.setForeground(new Color(51,51,51));
        int key = Integer.parseInt(inp);
        t.insert(key,false);
        
    }//GEN-LAST:event_addjbtnActionPerformed

    private void searchjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjbtnActionPerformed
        // TODO add your handling code here:
        String inp = inp_jtxt.getText();
        //StatusDisplayer.getDefault.setStatusText(" ");
       /// outfld.setVisible(true);
        outfld.setText("");
        inp_jtxt.setText("");
        reslbl.setForeground(new Color(255,255,255));
        int key = Integer.parseInt(inp);
        t.search(key);
        outfld.setText(t.result);
       // outfld.setText("Sup punk");
        System.out.println("out: "+ t.result);
        if(t.result.equals("") == true){
            outfld.setText("Not Found");
        }
    }//GEN-LAST:event_searchjbtnActionPerformed

    private void displayjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayjbtnActionPerformed
        // TODO add your handling code here:
        Table.sho = "";
        t.show_table(false);
        displayfld.setText("");
        displayfld.setText(Table.sho);
        System.out.println(Table.sho);
    }//GEN-LAST:event_displayjbtnActionPerformed

    private void inp_jtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inp_jtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inp_jtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Headlbl;
    private javax.swing.JButton addjbtn;
    private javax.swing.JTextArea displayfld;
    private javax.swing.JButton displayjbtn;
    private javax.swing.JLabel inp_jlbl;
    private javax.swing.JTextField inp_jtxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField outfld;
    private javax.swing.JLabel reslbl;
    private javax.swing.JButton searchjbtn;
    // End of variables declaration//GEN-END:variables
}
